### ISSUE TITLE
Erreur lors de l'appel depuis un autre dossier et ajout de -o

### ISSUE THREAD

**Issue by Nimon77** [nirae/generateur_attestation_sortie#3]
Bonjour,
Il y a une erreur lorsque l'on appel app.py depuis un autre dossier, le pdf n'es pas renommer en `{user}_attestation.pdf`.
Exemple : `./generateur_attestation_sortie/app.py -c ./config.yaml`
<img width="312" alt="Capture d’écran 2020-11-04 à 16 16 54" src="https://user-images.githubusercontent.com/11821952/98130500-9b1c3700-1eba-11eb-8b2b-14706dbe342f.png">
<img width="236" alt="Capture d’écran 2020-11-04 à 16 17 57" src="https://user-images.githubusercontent.com/11821952/98130512-9d7e9100-1eba-11eb-9010-ea58ae3f4a6c.png">

Il serais sympa d'avoir aussi une option `-o` pour permettre de choisir le dossier d'output des pdf.

Merci !

**Comment by nirae** [comment]
Le problème de path quand le script et appelé depuis un autre dossier est fix dans la pull request https://github.com/nirae/generateur_attestation_sortie/pull/4

Dans la même pull request, j'ai ajouté l'option -o pour choisir le nom et le path du fichier de sortie. Par defaut il reste dans le repertoire d'ou est appelé le script et se nomme {user}_attestation.pdf

Dis moi si ça résout bien le problème!

**Comment by Nimon77** [comment]
Je viens d'essayer, tout est bon !
